SELECT A.STOK_KODU, A.STOK_ADI, SUM( B.MIKTAR ) , B.BF, ROUND( SUM( B.MIKTAR ) * B.BF, 2 )
FROM sthar AS B
INNER JOIN tblstsabit AS A ON A.STOK_KODU = B.STOK_KODU
WHERE KAYNAK = '@merkezkod@'
AND HEDEF = '@carikod@'
AND TARIH >= (DATE_FORMAT(NOW() ,'%Y-01-01'))
AND TARIH <= NOW()
GROUP BY A.STOK_KODU
