select B.FATIRS_NO,B.KAYITYAPANKUL,Convert(VARCHAR, B.KAYITTARIHI, 120),CONVERT(VARBINARY(MAX),C.CARI_ISIM),
B.GENELTOPLAM,Convert(VARCHAR, B.TARIH, 104),Convert(VARCHAR, CH.VADE_TARIHI, 104),Convert(VARCHAR, CH.DUZELTMETARIHI, 120),CONVERT(VARBINARY(MAX),B.ACIKLAMA),B.CARI_KODU from TBLFATUIRS AS B
INNER JOIN TBLCASABIT AS C ON B.CARI_KODU=C.CARI_KOD
INNER JOIN TBLCAHAR AS CH ON CH.CARI_KOD=B.CARI_KODU AND CH.BELGE_NO=B.FATIRS_NO
WHERE B.KAYITTARIHI>NOW()-@GUN AND B.FTIRSIP IN (2,4)
ORDER BY B.KAYITTARIHI DESC